### ISSUE TITLE
TODO by nQuisition#1284

### ISSUE THREAD

**Issue by nQuisition** [nQuisition/illusions-bot#3]
**Submitted by**
nQuisition#1284

**Content**
- [x] Add better handling of subcommands
- [x] Add automatic command-level permission checks based on a field 
- [x] Hide inaccessible commands from !commands list
- [x] Do not allow empty suggests/bugs 
- [x] Ignore empty strings in !todo command when vertical bar is present
